// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_AkxswzLcVuLoRejBHSC-Yt7pNi_kleI',
    appId: '1:699606428027:web:3f633bc683d373ea0d35de',
    messagingSenderId: '699606428027',
    projectId: 'whatsapp-clone-bce8d',
    authDomain: 'whatsapp-clone-bce8d.firebaseapp.com',
    storageBucket: 'whatsapp-clone-bce8d.appspot.com',
    measurementId: 'G-BSZS1ES9JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCSeLEhgmGt6QddSZjvywt92k7VxdZF0',
    appId: '1:699606428027:android:b2a7d2e0aff46bbe0d35de',
    messagingSenderId: '699606428027',
    projectId: 'whatsapp-clone-bce8d',
    storageBucket: 'whatsapp-clone-bce8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoSR2CdzsGhvOOrlHQdBbJb7FCrJ4ppbw',
    appId: '1:699606428027:ios:65a91b7031db7e010d35de',
    messagingSenderId: '699606428027',
    projectId: 'whatsapp-clone-bce8d',
    storageBucket: 'whatsapp-clone-bce8d.appspot.com',
    iosClientId:
        '699606428027-qv0srnolebcld37badfmmths1od4o3tv.apps.googleusercontent.com',
    iosBundleId: 'com.whatsappclone.in',
  );
}
